### PR TITLE
Fixed the conditional logic for SELECT, RADIO and CHECKBOX

### PR DESCRIPTION
**Pull request by stackpond**
The fix addresses issues related to conditional evaluation for SELECT, RADIO & CHECKBOX elements. 

For SELECT fix, the tagName value is all caps as per https://developer.mozilla.org/en-US/docs/Web/API/Element/tagName. 

For RADIO and CHECKBOX fix, there can be multiple elements in a group, hence they need to have a common group name.

### CODE REVIEW

**Comment by kevinchappell** [comment]
@stackpond thanks for opening this PR, i planned to go through it tonight. Just curious why did you closed it?

**Comment by stackpond** [comment]
Hi Kevin

I was not sure if anyone would look at the PR. I have reopened the PR for
you to have a look. Sorry for the trouble :)

Regards
Sushant

**Comment by kevinchappell** [comment]
Thanks, @stackpond . im pretty slow getting to PRs but usually do get to them. Thanks again 👍

**Comment by kevinchappell** [comment]
great work! merging

**Pull request merged**
