### PR TITLE
feat: added sticky function to controls container

### PR DESCRIPTION
**Pull request by markandrewkato**
Added a stickyControls function to the controls container when editing.

### CODE REVIEW

**Comment by kevinchappell** [comment]
Awesome work! Thank you!

**Comment by markandrewkato** [comment]
@kevinchappell Happy to help. Just one question, when will this PR be merged in the master branch? Asking because, this is my first time contributing to a plugin development. I don't know if I should use the PR request in my package.json or if the process of merging is quick, I'll just wait for it to be merged in the master. 

Also, I used yarn because I'm having a problem building the module using npm. I don't know if this has an impact with regard to installing using npm. But right now, I can't seem to install the package using npm.

Thanks!

**Comment by kevinchappell** [comment]
@markandrewkato yarn is good, I'll see what the issue could be with npm. Generally PRs are quick to merge. You used the correct commit format so a release should automatically be generated allowing you to install form npm instead of resorting to github.

I'm at work so not able to test at the moment but I don't see anything that would cause regression issue so will merge now. 

The new version should be available via `yarn add formeo` in about 10 minutes

**Comment by markandrewkato** [comment]
@kevinchappell got it. thank you.

**Pull request merged**
